/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   tui.h                                              :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: imhaimou <marvin@42.fr>                    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2018/10/07 15:57:35 by imhaimou          #+#    #+#             */
/*   Updated: 2018/10/07 16:05:32 by imhaimou         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#ifndef FT_TUI_H
# define FT_TUI_H

# include <time.h>
# include <ncurses.h>
# include "corewar.h"

# if !defined(VM_REG_NUMBER)
#  define VM_REG_NUMBER 16
# endif
# if !defined(VM_MAX_REG_NUMBER)
#  define VM_MAX_REG_NUMBER	VM_REG_NUMBER + 2
# endif

# if defined( __linux__) || defined(__linux)
#  define SCROLL_UP_BTN BUTTON4_PRESSED
#  define SCROLL_DOWN_BTN BUTTON5_PRESSED
# elif defined(__APPLE__)
#  define SCROLL_UP_BTN BUTTON5_PRESSED
#  define SCROLL_DOWN_BTN BUTTON4_PRESSED
# endif

# define VIM_DOWN				'j'
# define VIM_UP					'k'
# define VIM_RIGHT				'l'
# define VIM_LEFT				'h'

# define TUI_PLAY1				'p'
# define TUI_PLAY2				'P'
# define TUI_PLAY3				' '
# define TUI_PAUSE1				TUI_PLAY1
# define TUI_PAUSE2				TUI_PLAY2
# define TUI_PAUSE23			TUI_PLAY2
# define TUI_NEXT1				'n'
# define TUI_NEXT2				'N'
# define TUI_NEXT3				VIM_RIGHT
# define TUI_NEXT4				KEY_RIGHT
# define TUI_UP1				'+'
# define TUI_UP2				'u'
# define TUI_UP3				'U'
# define TUI_DOWN1				'-'
# define TUI_DOWN2				'd'
# define TUI_DOWN3				'D'
# define TUI_LIST_UP1			VIM_UP
# define TUI_LIST_UP2			KEY_UP
# define TUI_LIST_DOWN1			VIM_DOWN
# define TUI_LIST_DOWN2			KEY_DOWN

# define TUI_SELECT				KEY_ENTER

# define MEM_WIN_WIDTH			195
# define MEM_WIN_HEIGHT			66

# define INF_WIN_WIDTH			65
# define INF_WIN_HEIGHT			31

# define MAX_LATENCY			5
# define STAT_PAUSE				0
# define STAT_PLAY				1
# define DEFAULT_STAT			STAT_PAUSE
# define DEFAULT_SPEED			80

# define SPEED_FACTOR			0.0009991000f

# define SPEDD_CHANGE_FACTOR	5

# define TUI_STAT_HEIGHT		3
# define TUI_STAT_WIDTH			8
# define TUI_STAT_ORGN_X		MEM_WIN_WIDTH + 5
# define TUI_STAT_ORGN_Y		1

# define TUI_NEXT_HEIGHT		TUI_STAT_HEIGHT
# define TUI_NEXT_WIDTH			TUI_STAT_WIDTH
# define TUI_NEXT_ORGN_X		TUI_STAT_ORGN_X + TUI_STAT_WIDTH
# define TUI_NEXT_ORGN_Y		TUI_STAT_ORGN_Y

# define TUI_SPEED_HEIGHT		TUI_STAT_HEIGHT
# define TUI_SPEED_WIDTH		24
# define TUI_SPEED_ORGN_X		TUI_NEXT_ORGN_X + TUI_NEXT_WIDTH
# define TUI_SPEED_ORGN_Y		TUI_STAT_ORGN_Y

# define TUI_SPEED_CHAR_WIDTH	11

# define TUI_HIGH_HEIGHT		TUI_STAT_HEIGHT
# define TUI_HIGH_WIDTH			TUI_STAT_WIDTH
# define TUI_HIGH_ORGN_X		TUI_SPEED_ORGN_X + TUI_SPEED_WIDTH
# define TUI_HIGH_ORGN_Y		TUI_STAT_ORGN_Y

# define TUI_LOW_HEIGHT			TUI_STAT_HEIGHT
# define TUI_LOW_WIDTH			TUI_STAT_WIDTH
# define TUI_LOW_ORGN_X			TUI_HIGH_ORGN_X + TUI_HIGH_WIDTH
# define TUI_LOW_ORGN_Y			TUI_STAT_ORGN_Y

# define TUI_P1_NUM_HEIGHT		TUI_STAT_HEIGHT
# define TUI_P1_NUM_WIDTH		10
# define TUI_P1_NUM_ORGN_X		MEM_WIN_WIDTH + 2
# define TUI_P1_NUM_ORGN_Y		TUI_STAT_ORGN_Y + TUI_STAT_HEIGHT + 1

# define TUI_P2_NUM_HEIGHT		TUI_STAT_HEIGHT
# define TUI_P2_NUM_WIDTH		10
# define TUI_P2_NUM_ORGN_X		TUI_P1_NUM_ORGN_X
# define TUI_P2_NUM_ORGN_Y		TUI_P1_NUM_ORGN_Y + TUI_P1_NUM_HEIGHT

# define TUI_P3_NUM_HEIGHT		TUI_STAT_HEIGHT
# define TUI_P3_NUM_WIDTH		10
# define TUI_P3_NUM_ORGN_X		TUI_P1_NUM_ORGN_X
# define TUI_P3_NUM_ORGN_Y		TUI_P2_NUM_ORGN_Y + TUI_P2_NUM_HEIGHT

# define TUI_P4_NUM_HEIGHT		TUI_STAT_HEIGHT
# define TUI_P4_NUM_WIDTH		10
# define TUI_P4_NUM_ORGN_X		TUI_P1_NUM_ORGN_X
# define TUI_P4_NUM_ORGN_Y		TUI_P3_NUM_ORGN_Y + TUI_P3_NUM_HEIGHT

# define TUI_P1_NAME_HEIGHT		TUI_STAT_HEIGHT
# define TUI_P1_NAME_WIDTH		51
# define TUI_P1_NAME_ORGN_X		TUI_P1_NUM_ORGN_X + TUI_P1_NUM_WIDTH
# define TUI_P1_NAME_ORGN_Y		TUI_P1_NUM_ORGN_Y

# define TUI_P2_NAME_HEIGHT		TUI_STAT_HEIGHT
# define TUI_P2_NAME_WIDTH		TUI_P1_NAME_WIDTH
# define TUI_P2_NAME_ORGN_X		TUI_P1_NAME_ORGN_X
# define TUI_P2_NAME_ORGN_Y		TUI_P2_NUM_ORGN_Y

# define TUI_P3_NAME_HEIGHT		TUI_STAT_HEIGHT
# define TUI_P3_NAME_WIDTH		TUI_P1_NAME_WIDTH
# define TUI_P3_NAME_ORGN_X		TUI_P1_NAME_ORGN_X
# define TUI_P3_NAME_ORGN_Y		TUI_P3_NUM_ORGN_Y

# define TUI_P4_NAME_HEIGHT		TUI_STAT_HEIGHT
# define TUI_P4_NAME_WIDTH		TUI_P1_NAME_WIDTH
# define TUI_P4_NAME_ORGN_X		TUI_P1_NAME_ORGN_X
# define TUI_P4_NAME_ORGN_Y		TUI_P4_NUM_ORGN_Y

# define TUI_CYCLE_HEIGHT		TUI_STAT_HEIGHT
# define TUI_CYCLE_WIDTH		29
# define TUI_CYCLE_ORGN_X		TUI_P1_NUM_ORGN_X + 1
# define TUI_CYCLE_ORGN_Y		TUI_P4_NUM_ORGN_Y + TUI_P4_NUM_HEIGHT + 1

# define TUI_CYCLE_VAL_HEIGHT	TUI_STAT_HEIGHT
# define TUI_CYCLE_VAL_WIDTH	TUI_CYCLE_WIDTH
# define TUI_CYCLE_VAL_ORGN_X	TUI_CYCLE_ORGN_X
# define TUI_CYCLE_VAL_ORGN_Y	TUI_CYCLE_ORGN_Y + TUI_CYCLE_HEIGHT

# define TUI_CYCLE_TO_DIE_HEIGHT		TUI_STAT_HEIGHT
# define TUI_CYCLE_TO_DIE_WIDTH			TUI_CYCLE_WIDTH
# define TUI_CYCLE_TO_DIE_ORGN_X		TUI_CYCLE_ORGN_X + TUI_CYCLE_WIDTH + 1
# define TUI_CYCLE_TO_DIE_ORGN_Y		TUI_CYCLE_ORGN_Y

# define TUI_CYCLE_TO_DIE_VAL_HEIGHT TUI_STAT_HEIGHT
# define TUI_CYCLE_TO_DIE_VAL_WIDTH	 TUI_CYCLE_WIDTH
# define TUI_CYCLE_TO_DIE_VAL_ORGN_X TUI_CYCLE_TO_DIE_ORGN_X
# define TUI_CYCLE_TO_DIE_VAL_ORGN_Y TUI_CYCLE_ORGN_Y + TUI_CYCLE_TO_DIE_HEIGHT

# define TUI_LIVE_HEIGHT		TUI_STAT_HEIGHT
# define TUI_LIVE_WIDTH			TUI_CYCLE_WIDTH
# define TUI_LIVE_ORGN_X		TUI_CYCLE_ORGN_X
# define TUI_LIVE_ORGN_Y		TUI_CYCLE_VAL_ORGN_Y + TUI_CYCLE_VAL_HEIGHT

# define TUI_LIVE_VAL_HEIGHT	TUI_STAT_HEIGHT
# define TUI_LIVE_VAL_WIDTH		TUI_LIVE_WIDTH
# define TUI_LIVE_VAL_ORGN_X	TUI_LIVE_ORGN_X
# define TUI_LIVE_VAL_ORGN_Y	TUI_LIVE_ORGN_Y + TUI_LIVE_HEIGHT

# define TUI_MAX_PROC_HEIGHT	TUI_STAT_HEIGHT
# define TUI_MAX_PROC_WIDTH		TUI_CYCLE_WIDTH
# define TUI_MAX_PROC_ORGN_X	TUI_CYCLE_TO_DIE_ORGN_X
# define TUI_MAX_PROC_ORGN_Y	TUI_LIVE_ORGN_Y

# define TUI_MAX_PROC_VAL_HEIGHT	TUI_STAT_HEIGHT
# define TUI_MAX_PROC_VAL_WIDTH		TUI_CYCLE_WIDTH
# define TUI_MAX_PROC_VAL_ORGN_X	TUI_CYCLE_TO_DIE_ORGN_X
# define TUI_MAX_PROC_VAL_ORGN_Y	TUI_MAX_PROC_ORGN_Y + TUI_MAX_PROC_HEIGHT

# define TUI_PROC_HEAD_HEIGHT	TUI_STAT_HEIGHT + 0
# define TUI_PROC_HEAD_WIDTH	INF_WIN_WIDTH
# define TUI_PROC_HEAD_ORGN_X	MEM_WIN_WIDTH
# define TUI_PROC_HEAD_ORGN_Y	INF_WIN_HEIGHT

# define TUI_PROC_LIST_HEIGHT	66 - INF_WIN_HEIGHT - TUI_PROC_HEAD_HEIGHT
# define TUI_PROC_LIST_WIDTH	INF_WIN_WIDTH
# define TUI_PROC_LIST_ORGN_X	TUI_PROC_HEAD_ORGN_X
# define TUI_PROC_LIST_ORGN_Y	TUI_PROC_HEAD_ORGN_Y + TUI_PROC_HEAD_HEIGHT

# define TUI_PROC_BOX_HEIGHT	8
# define TUI_PROC_BOX_WIDTH		INF_WIN_WIDTH
# define TUI_PROC_BOX_ORGN_X	MEM_WIN_WIDTH + INF_WIN_WIDTH
# define TUI_PROC_BOX_ORGN_Y	0

# define TUI_REG_BF_BOX_HEIGHT	29
# define TUI_REG_BF_BOX_WIDTH	TUI_PROC_BOX_WIDTH
# define TUI_REG_BF_BOX_ORGN_X	TUI_PROC_BOX_ORGN_X
# define TUI_REG_BF_BOX_ORGN_Y	TUI_PROC_BOX_ORGN_Y + TUI_PROC_BOX_HEIGHT

# define TUI_REG_BF_NAME_HEIGHT		3
# define TUI_REG_BF_NAME_WIDTH		8

# define TUI_REG_BF_HEIGHT		TUI_REG_BF_NAME_HEIGHT
# define TUI_REG_BF_WIDTH		23

# define TUI_REG_BF_NAME0_ORGN_X	TUI_REG_BF_BOX_ORGN_X + 1
# define TUI_REG_BF_NAME0_ORGN_Y	TUI_REG_BF_BOX_ORGN_Y + 1
# define TUI_REG_BF0_ORGN_X	TUI_REG_BF_NAME0_ORGN_X + 8
# define TUI_REG_BF0_ORGN_Y	TUI_REG_BF_NAME0_ORGN_Y

# define TUI_REG_BF_NAME1_ORGN_X	TUI_REG_BF_NAME0_ORGN_X
# define TUI_REG_BF_NAME1_ORGN_Y	TUI_REG_BF_NAME0_ORGN_Y + 3
# define TUI_REG_BF1_ORGN_X	TUI_REG_BF0_ORGN_X
# define TUI_REG_BF1_ORGN_Y	TUI_REG_BF0_ORGN_Y + 3

# define TUI_REG_BF_NAME2_ORGN_X	TUI_REG_BF_NAME0_ORGN_X
# define TUI_REG_BF_NAME2_ORGN_Y	TUI_REG_BF_NAME1_ORGN_Y + 3
# define TUI_REG_BF2_ORGN_X	TUI_REG_BF0_ORGN_X
# define TUI_REG_BF2_ORGN_Y	TUI_REG_BF1_ORGN_Y + 3

# define TUI_REG_BF_NAME3_ORGN_X	TUI_REG_BF_NAME0_ORGN_X
# define TUI_REG_BF_NAME3_ORGN_Y	TUI_REG_BF_NAME2_ORGN_Y + 3
# define TUI_REG_BF3_ORGN_X	TUI_REG_BF0_ORGN_X
# define TUI_REG_BF3_ORGN_Y	TUI_REG_BF2_ORGN_Y + 3

# define TUI_REG_BF_NAME4_ORGN_X	TUI_REG_BF_NAME0_ORGN_X
# define TUI_REG_BF_NAME4_ORGN_Y	TUI_REG_BF_NAME3_ORGN_Y + 3
# define TUI_REG_BF4_ORGN_X	TUI_REG_BF0_ORGN_X
# define TUI_REG_BF4_ORGN_Y	TUI_REG_BF3_ORGN_Y + 3

# define TUI_REG_BF_NAME5_ORGN_X	TUI_REG_BF_NAME0_ORGN_X
# define TUI_REG_BF_NAME5_ORGN_Y	TUI_REG_BF_NAME4_ORGN_Y + 3
# define TUI_REG_BF5_ORGN_X	TUI_REG_BF0_ORGN_X
# define TUI_REG_BF5_ORGN_Y	TUI_REG_BF4_ORGN_Y + 3

# define TUI_REG_BF_NAME6_ORGN_X	TUI_REG_BF_NAME0_ORGN_X
# define TUI_REG_BF_NAME6_ORGN_Y	TUI_REG_BF_NAME5_ORGN_Y + 3
# define TUI_REG_BF6_ORGN_X	TUI_REG_BF0_ORGN_X
# define TUI_REG_BF6_ORGN_Y	TUI_REG_BF5_ORGN_Y + 3

# define TUI_REG_BF_NAME7_ORGN_X	TUI_REG_BF_NAME0_ORGN_X
# define TUI_REG_BF_NAME7_ORGN_Y	TUI_REG_BF_NAME6_ORGN_Y + 3
# define TUI_REG_BF7_ORGN_X	TUI_REG_BF0_ORGN_X
# define TUI_REG_BF7_ORGN_Y	TUI_REG_BF6_ORGN_Y + 3

# define TUI_REG_BF_NAME8_ORGN_X	TUI_REG_BF_NAME0_ORGN_X
# define TUI_REG_BF_NAME8_ORGN_Y	TUI_REG_BF_NAME7_ORGN_Y + 3
# define TUI_REG_BF8_ORGN_X	TUI_REG_BF0_ORGN_X
# define TUI_REG_BF8_ORGN_Y	TUI_REG_BF7_ORGN_Y + 3

# define TUI_REG_BF_NAME17_ORGN_X	TUI_REG_BF_NAME0_ORGN_X + 8 + 23
# define TUI_REG_BF_NAME17_ORGN_Y	TUI_REG_BF_NAME0_ORGN_Y
# define TUI_REG_BF17_ORGN_X	TUI_REG_BF_NAME17_ORGN_X + 8
# define TUI_REG_BF17_ORGN_Y	TUI_REG_BF0_ORGN_Y

# define TUI_REG_BF_NAME9_ORGN_X	TUI_REG_BF_NAME17_ORGN_X
# define TUI_REG_BF_NAME9_ORGN_Y	TUI_REG_BF_NAME17_ORGN_Y + 3
# define TUI_REG_BF9_ORGN_X	TUI_REG_BF17_ORGN_X
# define TUI_REG_BF9_ORGN_Y	TUI_REG_BF17_ORGN_Y + 3

# define TUI_REG_BF_NAME10_ORGN_X	TUI_REG_BF_NAME17_ORGN_X
# define TUI_REG_BF_NAME10_ORGN_Y	TUI_REG_BF_NAME9_ORGN_Y + 3
# define TUI_REG_BF10_ORGN_X	TUI_REG_BF17_ORGN_X
# define TUI_REG_BF10_ORGN_Y	TUI_REG_BF9_ORGN_Y + 3

# define TUI_REG_BF_NAME11_ORGN_X	TUI_REG_BF_NAME17_ORGN_X
# define TUI_REG_BF_NAME11_ORGN_Y	TUI_REG_BF_NAME10_ORGN_Y + 3
# define TUI_REG_BF11_ORGN_X	TUI_REG_BF17_ORGN_X
# define TUI_REG_BF11_ORGN_Y	TUI_REG_BF10_ORGN_Y + 3

# define TUI_REG_BF_NAME12_ORGN_X	TUI_REG_BF_NAME17_ORGN_X
# define TUI_REG_BF_NAME12_ORGN_Y	TUI_REG_BF_NAME11_ORGN_Y + 3
# define TUI_REG_BF12_ORGN_X	TUI_REG_BF17_ORGN_X
# define TUI_REG_BF12_ORGN_Y	TUI_REG_BF11_ORGN_Y + 3

# define TUI_REG_BF_NAME13_ORGN_X	TUI_REG_BF_NAME17_ORGN_X
# define TUI_REG_BF_NAME13_ORGN_Y	TUI_REG_BF_NAME12_ORGN_Y + 3
# define TUI_REG_BF13_ORGN_X	TUI_REG_BF17_ORGN_X
# define TUI_REG_BF13_ORGN_Y	TUI_REG_BF12_ORGN_Y + 3

# define TUI_REG_BF_NAME14_ORGN_X	TUI_REG_BF_NAME17_ORGN_X
# define TUI_REG_BF_NAME14_ORGN_Y	TUI_REG_BF_NAME13_ORGN_Y + 3
# define TUI_REG_BF14_ORGN_X	TUI_REG_BF17_ORGN_X
# define TUI_REG_BF14_ORGN_Y	TUI_REG_BF13_ORGN_Y + 3

# define TUI_REG_BF_NAME15_ORGN_X	TUI_REG_BF_NAME17_ORGN_X
# define TUI_REG_BF_NAME15_ORGN_Y	TUI_REG_BF_NAME14_ORGN_Y + 3
# define TUI_REG_BF15_ORGN_X	TUI_REG_BF17_ORGN_X
# define TUI_REG_BF15_ORGN_Y	TUI_REG_BF14_ORGN_Y + 3

# define TUI_REG_BF_NAME16_ORGN_X	TUI_REG_BF_NAME17_ORGN_X
# define TUI_REG_BF_NAME16_ORGN_Y	TUI_REG_BF_NAME15_ORGN_Y + 3
# define TUI_REG_BF16_ORGN_X	TUI_REG_BF17_ORGN_X
# define TUI_REG_BF16_ORGN_Y	TUI_REG_BF15_ORGN_Y + 3

# define TUI_REG_AF_BOX_HEIGHT	TUI_REG_BF_BOX_HEIGHT
# define TUI_REG_AF_BOX_WIDTH	TUI_REG_BF_BOX_WIDTH
# define TUI_REG_AF_BOX_ORGN_X	TUI_REG_BF_BOX_ORGN_X
# define TUI_REG_AF_BOX_ORGN_Y	TUI_REG_BF_BOX_ORGN_Y + TUI_REG_BF_BOX_HEIGHT

# define TUI_REG_AF_NAME_HEIGHT		3
# define TUI_REG_AF_NAME_WIDTH		8

# define TUI_REG_AF_HEIGHT		TUI_REG_AF_NAME_HEIGHT
# define TUI_REG_AF_WIDTH		23

# define TUI_REG_AF_NAME0_ORGN_X	TUI_REG_AF_BOX_ORGN_X + 1
# define TUI_REG_AF_NAME0_ORGN_Y	TUI_REG_AF_BOX_ORGN_Y + 1
# define TUI_REG_AF0_ORGN_X			TUI_REG_AF_NAME0_ORGN_X + 8
# define TUI_REG_AF0_ORGN_Y			TUI_REG_AF_NAME0_ORGN_Y

# define TUI_REG_AF_NAME1_ORGN_X	TUI_REG_AF_NAME0_ORGN_X
# define TUI_REG_AF_NAME1_ORGN_Y	TUI_REG_AF_NAME0_ORGN_Y + 3
# define TUI_REG_AF1_ORGN_X			TUI_REG_AF0_ORGN_X
# define TUI_REG_AF1_ORGN_Y			TUI_REG_AF0_ORGN_Y + 3

# define TUI_REG_AF_NAME2_ORGN_X	TUI_REG_AF_NAME0_ORGN_X
# define TUI_REG_AF_NAME2_ORGN_Y	TUI_REG_AF_NAME1_ORGN_Y + 3
# define TUI_REG_AF2_ORGN_X			TUI_REG_AF0_ORGN_X
# define TUI_REG_AF2_ORGN_Y			TUI_REG_AF1_ORGN_Y + 3

# define TUI_REG_AF_NAME3_ORGN_X	TUI_REG_AF_NAME0_ORGN_X
# define TUI_REG_AF_NAME3_ORGN_Y	TUI_REG_AF_NAME2_ORGN_Y + 3
# define TUI_REG_AF3_ORGN_X			TUI_REG_AF0_ORGN_X
# define TUI_REG_AF3_ORGN_Y			TUI_REG_AF2_ORGN_Y + 3

# define TUI_REG_AF_NAME4_ORGN_X	TUI_REG_AF_NAME0_ORGN_X
# define TUI_REG_AF_NAME4_ORGN_Y	TUI_REG_AF_NAME3_ORGN_Y + 3
# define TUI_REG_AF4_ORGN_X			TUI_REG_AF0_ORGN_X
# define TUI_REG_AF4_ORGN_Y			TUI_REG_AF3_ORGN_Y + 3

# define TUI_REG_AF_NAME5_ORGN_X	TUI_REG_AF_NAME0_ORGN_X
# define TUI_REG_AF_NAME5_ORGN_Y	TUI_REG_AF_NAME4_ORGN_Y + 3
# define TUI_REG_AF5_ORGN_X			TUI_REG_AF0_ORGN_X
# define TUI_REG_AF5_ORGN_Y			TUI_REG_AF4_ORGN_Y + 3

# define TUI_REG_AF_NAME6_ORGN_X	TUI_REG_AF_NAME0_ORGN_X
# define TUI_REG_AF_NAME6_ORGN_Y	TUI_REG_AF_NAME5_ORGN_Y + 3
# define TUI_REG_AF6_ORGN_X			TUI_REG_AF0_ORGN_X
# define TUI_REG_AF6_ORGN_Y			TUI_REG_AF5_ORGN_Y + 3

# define TUI_REG_AF_NAME7_ORGN_X	TUI_REG_AF_NAME0_ORGN_X
# define TUI_REG_AF_NAME7_ORGN_Y	TUI_REG_AF_NAME6_ORGN_Y + 3
# define TUI_REG_AF7_ORGN_X			TUI_REG_AF0_ORGN_X
# define TUI_REG_AF7_ORGN_Y			TUI_REG_AF6_ORGN_Y + 3

# define TUI_REG_AF_NAME8_ORGN_X	TUI_REG_AF_NAME0_ORGN_X
# define TUI_REG_AF_NAME8_ORGN_Y	TUI_REG_AF_NAME7_ORGN_Y + 3
# define TUI_REG_AF8_ORGN_X			TUI_REG_AF0_ORGN_X
# define TUI_REG_AF8_ORGN_Y			TUI_REG_AF7_ORGN_Y + 3

# define TUI_REG_AF_NAME17_ORGN_X	TUI_REG_AF_NAME0_ORGN_X + 8 + 23
# define TUI_REG_AF_NAME17_ORGN_Y	TUI_REG_AF_NAME0_ORGN_Y
# define TUI_REG_AF17_ORGN_X		TUI_REG_AF_NAME17_ORGN_X + 8
# define TUI_REG_AF17_ORGN_Y		TUI_REG_AF0_ORGN_Y

# define TUI_REG_AF_NAME9_ORGN_X	TUI_REG_AF_NAME17_ORGN_X
# define TUI_REG_AF_NAME9_ORGN_Y	TUI_REG_AF_NAME17_ORGN_Y + 3
# define TUI_REG_AF9_ORGN_X			TUI_REG_AF17_ORGN_X
# define TUI_REG_AF9_ORGN_Y			TUI_REG_AF17_ORGN_Y + 3

# define TUI_REG_AF_NAME10_ORGN_X	TUI_REG_AF_NAME17_ORGN_X
# define TUI_REG_AF_NAME10_ORGN_Y	TUI_REG_AF_NAME9_ORGN_Y + 3
# define TUI_REG_AF10_ORGN_X		TUI_REG_AF17_ORGN_X
# define TUI_REG_AF10_ORGN_Y		TUI_REG_AF9_ORGN_Y + 3

# define TUI_REG_AF_NAME11_ORGN_X	TUI_REG_AF_NAME17_ORGN_X
# define TUI_REG_AF_NAME11_ORGN_Y	TUI_REG_AF_NAME10_ORGN_Y + 3
# define TUI_REG_AF11_ORGN_X		TUI_REG_AF17_ORGN_X
# define TUI_REG_AF11_ORGN_Y		TUI_REG_AF10_ORGN_Y + 3

# define TUI_REG_AF_NAME12_ORGN_X	TUI_REG_AF_NAME17_ORGN_X
# define TUI_REG_AF_NAME12_ORGN_Y	TUI_REG_AF_NAME11_ORGN_Y + 3
# define TUI_REG_AF12_ORGN_X		TUI_REG_AF17_ORGN_X
# define TUI_REG_AF12_ORGN_Y		TUI_REG_AF11_ORGN_Y + 3

# define TUI_REG_AF_NAME13_ORGN_X	TUI_REG_AF_NAME17_ORGN_X
# define TUI_REG_AF_NAME13_ORGN_Y	TUI_REG_AF_NAME12_ORGN_Y + 3
# define TUI_REG_AF13_ORGN_X		TUI_REG_AF17_ORGN_X
# define TUI_REG_AF13_ORGN_Y		TUI_REG_AF12_ORGN_Y + 3

# define TUI_REG_AF_NAME14_ORGN_X	TUI_REG_AF_NAME17_ORGN_X
# define TUI_REG_AF_NAME14_ORGN_Y	TUI_REG_AF_NAME13_ORGN_Y + 3
# define TUI_REG_AF14_ORGN_X		TUI_REG_AF17_ORGN_X
# define TUI_REG_AF14_ORGN_Y		TUI_REG_AF13_ORGN_Y + 3

# define TUI_REG_AF_NAME15_ORGN_X	TUI_REG_AF_NAME17_ORGN_X
# define TUI_REG_AF_NAME15_ORGN_Y	TUI_REG_AF_NAME14_ORGN_Y + 3
# define TUI_REG_AF15_ORGN_X		TUI_REG_AF17_ORGN_X
# define TUI_REG_AF15_ORGN_Y		TUI_REG_AF14_ORGN_Y + 3

# define TUI_REG_AF_NAME16_ORGN_X	TUI_REG_AF_NAME17_ORGN_X
# define TUI_REG_AF_NAME16_ORGN_Y	TUI_REG_AF_NAME15_ORGN_Y + 3
# define TUI_REG_AF16_ORGN_X		TUI_REG_AF17_ORGN_X
# define TUI_REG_AF16_ORGN_Y		TUI_REG_AF15_ORGN_Y + 3

# define TUI_PROCESS_HEIGHT			3
# define TUI_PROCESS_WIDTH			TUI_PROC_LIST_WIDTH - 2

# define TUI_PROCESS1_ORGN_X			TUI_PROC_LIST_ORGN_X + 1
# define TUI_PROCESS1_ORGN_Y			TUI_PROC_LIST_ORGN_Y + 1

# define TUI_PROCESS2_ORGN_X			TUI_PROCESS1_ORGN_X
# define TUI_PROCESS2_ORGN_Y			TUI_PROCESS1_ORGN_Y + 3

# define TUI_PROCESS3_ORGN_X			TUI_PROCESS1_ORGN_X
# define TUI_PROCESS3_ORGN_Y			TUI_PROCESS2_ORGN_Y + 3

# define TUI_PROCESS4_ORGN_X			TUI_PROCESS1_ORGN_X
# define TUI_PROCESS4_ORGN_Y			TUI_PROCESS3_ORGN_Y + 3

# define TUI_PROCESS5_ORGN_X			TUI_PROCESS1_ORGN_X
# define TUI_PROCESS5_ORGN_Y			TUI_PROCESS4_ORGN_Y + 3

# define TUI_PROCESS6_ORGN_X			TUI_PROCESS1_ORGN_X
# define TUI_PROCESS6_ORGN_Y			TUI_PROCESS5_ORGN_Y + 3

# define TUI_PROCESS7_ORGN_X			TUI_PROCESS1_ORGN_X
# define TUI_PROCESS7_ORGN_Y			TUI_PROCESS6_ORGN_Y + 3

# define TUI_PROCESS8_ORGN_X			TUI_PROCESS1_ORGN_X
# define TUI_PROCESS8_ORGN_Y			TUI_PROCESS7_ORGN_Y + 3

# define TUI_PROCESS9_ORGN_X			TUI_PROCESS1_ORGN_X
# define TUI_PROCESS9_ORGN_Y			TUI_PROCESS8_ORGN_Y + 3

# define TUI_PROCESS10_ORGN_X			TUI_PROCESS1_ORGN_X
# define TUI_PROCESS10_ORGN_Y			TUI_PROCESS9_ORGN_Y + 3

# define MAX_PROC_IN_LIST			10
# define DEFAULT_SELECTED			0

typedef struct	s_tui
{
	WINDOW *stat;
	WINDOW *next;
	WINDOW *speed;
	WINDOW *high;
	WINDOW *low;
	WINDOW *p_num[4];
	WINDOW *p_name[4];
	WINDOW *cycle;
	WINDOW *cycle_val;
	WINDOW *cycle_to_die;
	WINDOW *cycle_to_die_val;
	WINDOW *live;
	WINDOW *live_val;
	WINDOW *max_proc;
	WINDOW *max_proc_val;
	WINDOW *proc_head;
	WINDOW *proc_list;
	WINDOW *process[MAX_PROC_IN_LIST];
	WINDOW *proc_box;
	WINDOW *reg_bf_box;
	WINDOW *reg_bf_name[VM_MAX_REG_NUMBER];
	WINDOW *reg_bf[VM_MAX_REG_NUMBER];
	WINDOW *reg_af_box;
	WINDOW *reg_af_name[VM_MAX_REG_NUMBER];
	WINDOW *reg_af[VM_MAX_REG_NUMBER];
	WINDOW *input;
	WINDOW *output;
}				t_tui;

#endif
